apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-devops
  labels:
    app: todo-devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-devops
  template:
    metadata:
      labels:
        app: todo-devops
    spec:
      containers:
      - name: todo-devops
        image: haythembekir20/todo-devops:latest
        ports:
        - containerPort: 8085

